<?php

namespace App\Http;

use Illuminate\Foundation\Http\Kernel as HttpKernel;

class Kernel extends HttpKernel
{
    /**
     * The application's global HTTP middleware stack.
     *
     * @var array
     */
    protected $middleware = [
    ];

    /**
     * The application's route middleware.
     *
     * @var array
     */
    protected $routeMiddleware = [
        'common.addUserAgent' => \App\Common\Http\Middleware\AddUserAgent::class,
        'common.addLanguages' => \App\Common\Http\Middleware\AddLanguages::class,
        'common.cookieQueue' => \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
        'common.resetDebuggerLog' => \App\Common\Http\Middleware\ResetDebuggerLog::class,
        'common.validateRequestValues' => \App\Common\Http\Middleware\ValidateRequestValues::class,
        'common.validateCookiesEnabled' => \App\Common\Http\Middleware\ValidateCookiesEnabled::class,
        'common.validateConnectionSecure' => \App\Common\Http\Middleware\ValidateConnectionSecure::class,
        'common.createCookiesEnabledCookie' => \App\Common\Http\Middleware\CreateCookiesEnabledCookie::class,
        'common.addRouteVariables' => \App\Common\Http\Middleware\AddRouteVariables::class,
        'common.addSettings' => \App\Common\Http\Middleware\AddSettings::class,
        'common.addHelp' => \App\Common\Http\Middleware\AddHelp::class,
        'common.admin.addStandardHeaders' => \App\Common\Http\Middleware\Admin\AddStandardHeaders::class,
        'common.admin.registerIp' => \App\Common\Http\Middleware\Admin\Authentication\RegisterIp::class,
        'common.admin.findWebUser' => \App\Common\Http\Middleware\Admin\Authentication\FindWebUser::class,
        'common.admin.findApiUser' => \App\Common\Http\Middleware\Admin\Authentication\FindApiUser::class,
        'common.admin.addUserOptions' => \App\Common\Http\Middleware\Admin\AddUserOptions::class,
        'common.admin.addColors' => \App\Common\Http\Middleware\Admin\AddColors::class,
        'common.admin.cleanTokens' => \App\Common\Http\Middleware\Admin\Authentication\CleanTokens::class,
        'common.admin.createRememberMe' => \App\Common\Http\Middleware\Admin\Authentication\CreateRememberMe::class,
        'common.admin.validateRememberMe' => \App\Common\Http\Middleware\Admin\Authentication\ValidateRememberMe::class,
        'common.admin.createPrepareLogin' => \App\Common\Http\Middleware\Admin\Authentication\CreatePrepareLogin::class,
        'common.admin.validatePrepareLogin' => \App\Common\Http\Middleware\Admin\Authentication\ValidatePrepareLogin::class,
        'common.admin.createLogin' => \App\Common\Http\Middleware\Admin\Authentication\CreateLogin::class,
        'common.admin.validateLogin' => \App\Common\Http\Middleware\Admin\Authentication\ValidateLogin::class,
        'common.admin.validateCredentials' => \App\Common\Http\Middleware\Admin\Authentication\ValidateCredentials::class,
        'common.admin.authenticate' => \App\Common\Http\Middleware\Admin\Authentication\Authenticate::class,
        'common.admin.logOut' => \App\Common\Http\Middleware\Admin\Authentication\LogOut::class,
        'common.site.addStandardHeaders' => \App\Common\Http\Middleware\Site\AddStandardHeaders::class,
        'common.site.registerIp' => \App\Common\Http\Middleware\Site\Authentication\RegisterIp::class,
        'common.site.getRouteLanguage' => \App\Common\Http\Middleware\Site\GetRouteLanguage::class,
        'common.site.getRoute' => \App\Common\Http\Middleware\Site\GetRoute::class,
        'common.site.truncateBaseDirFromRoute' => \App\Common\Http\Middleware\Site\TruncateBaseDirFromRoute::class,
        'common.site.addRoutes' => \App\Common\Http\Middleware\Site\AddRoutes::class,
        'common.site.findRoute' => \App\Common\Http\Middleware\Site\FindRoute::class,
        'games.site.addRoutes' => \App\Games\Http\Middleware\Site\AddRoutes::class,
        'games.site.addTranslations' => \App\Games\Http\Middleware\Site\AddTranslations::class,
        'games.site.addGames' => \App\Games\Http\Middleware\Site\AddGames::class,
        'games.site.getLanguage' => \App\Games\Http\Middleware\Site\GetLanguage::class,
        'games.site.getGame' => \App\Games\Http\Middleware\Site\GetGame::class,
        'games.site.addGameModules' => \App\Games\Http\Middleware\Site\AddGameModules::class,
        'games.site.addGameOptions' => \App\Games\Http\Middleware\Site\AddGameOptions::class,
        'siteAnimator.site.test' => \App\SiteAnimator\Http\Middleware\Site\Test::class,
        'siteAnimator.site.getLanguage' => \App\SiteAnimator\Http\Middleware\Site\GetLanguage::class,
        'siteAnimator.site.addIndexTranslations' => \App\SiteAnimator\Http\Middleware\Site\AddIndexTranslations::class,
        'siteAnimator.site.addLanguages' => \App\SiteAnimator\Http\Middleware\Site\AddLanguages::class,
        'siteAnimator.site.getApiLanguage' => \App\SiteAnimator\Http\Middleware\Site\GetApiLanguage::class,
        'siteAnimator.site.addSettings' => \App\SiteAnimator\Http\Middleware\Site\AddSettings::class,
        'siteAnimator.site.addSiteItems' => \App\SiteAnimator\Http\Middleware\Site\AddSiteItems::class,
        'siteAnimator.site.addFonts' => \App\SiteAnimator\Http\Middleware\Site\AddFonts::class,
        'siteAnimator.site.addColors' => \App\SiteAnimator\Http\Middleware\Site\AddColors::class,
        'siteAnimator.site.addCss' => \App\SiteAnimator\Http\Middleware\Site\AddCss::class,
        'siteAnimator.site.addAnimationSequences' => \App\SiteAnimator\Http\Middleware\Site\AddAnimationSequences::class,
        'siteAnimator.site.addShowNotPublic' => \App\SiteAnimator\Http\Middleware\Site\AddShowNotPublic::class,
        'siteAnimator.site.addPage' => \App\SiteAnimator\Http\Middleware\Site\AddPage::class,
        'siteAnimator.site.addBlogData' => \App\SiteAnimator\Http\Middleware\Site\Blog\AddBlogData::class,
        'siteAnimator.admin.truncateAdminFromRoute' => \App\SiteAnimator\Http\Middleware\Admin\TruncateAdminFromRoute::class,
        'siteAnimator.admin.getWebUser' => \App\SiteAnimator\Http\Middleware\Admin\GetWebUser::class,
        'siteAnimator.admin.truncateUserNameFromRoute' => \App\SiteAnimator\Http\Middleware\Admin\TruncateUserNameFromRoute::class,
        'siteAnimator.admin.addSiteItems' => \App\SiteAnimator\Http\Middleware\Admin\AddSiteItems::class,
        'siteAnimator.admin.addSiteLanguages' => \App\SiteAnimator\Http\Middleware\Admin\AddSiteLanguages::class,
        'siteAnimator.admin.addSiteIndexTranslations' => \App\SiteAnimator\Http\Middleware\Admin\AddSiteIndexTranslations::class,
        'admin.resetDebuggerLog' => \App\Http\Middleware\Admin\ResetDebuggerLog::class,
        'admin.validateLoginConnectionSecure' => \App\Http\Middleware\Admin\Authentication\ValidateLoginConnectionSecure::class,
        'admin.validateLoginName' => \App\Http\Middleware\Admin\Authentication\ValidateLoginName::class,
        'admin.createLoginToken' => \App\Http\Middleware\Admin\Authentication\CreateLoginToken::class,
        'admin.validateLoginToken' => \App\Http\Middleware\Admin\Authentication\ValidateLoginToken::class,
        'admin.cleanLoginTokens' => \App\Http\Middleware\Admin\Authentication\CleanLoginTokens::class,
        'admin.createLoginCookie' => \App\Http\Middleware\Admin\Authentication\CreateLoginCookie::class,
        'admin.validateLoginCookie' => \App\Http\Middleware\Admin\Authentication\ValidateLoginCookie::class,
        'admin.createPrepareLoginToken' => \App\Http\Middleware\Admin\Authentication\CreatePrepareLoginToken::class,
        'admin.validatePrepareLoginToken' => \App\Http\Middleware\Admin\Authentication\ValidatePrepareLoginToken::class,
        'admin.createPrepareLoginCookie' => \App\Http\Middleware\Admin\Authentication\CreatePrepareLoginCookie::class,
        'admin.validatePrepareLoginCookie' => \App\Http\Middleware\Admin\Authentication\ValidatePrepareLoginCookie::class,
        'admin.cleanLoginUserTokens' => \App\Http\Middleware\Admin\Authentication\CleanLoginUserTokens::class,
        'admin.validateCredentials' => \App\Http\Middleware\Admin\Authentication\ValidateCredentials::class,
        'admin.authenticate' => \App\Http\Middleware\Admin\Authentication\Authenticate::class,
        'admin.refreshJsonWebToken' => \App\Http\Middleware\Admin\Authentication\RefreshJsonWebToken::class,
        'admin.createPageToken' => \App\Http\Middleware\Admin\Authentication\CreatePageToken::class,
        'admin.test' => \App\Http\Middleware\Admin\Test::class,
        'admin.siteRoute' => \App\Http\Middleware\Admin\SiteRoute::class,
        'admin.colors' => \App\Http\Middleware\Admin\Colors::class,
        'admin.options' => \App\Http\Middleware\Admin\Options::class,
        'admin.adminVisitors' => \App\Http\Middleware\Admin\AdminVisitors::class,
        'admin.adminSiteTranslations' => \App\Http\Middleware\Admin\Site\AdminSiteTranslations::class,
        'admin.adminSiteOptions' => \App\Http\Middleware\Admin\Site\AdminSiteOptions::class,
        'admin.adminSiteColors' => \App\Http\Middleware\Admin\Site\AdminSiteColors::class,
        'admin.adminSitePages' => \App\Http\Middleware\Admin\Site\AdminSitePages::class,
        'admin.adminSiteParts' => \App\Http\Middleware\Admin\Site\AdminSiteParts::class,
        'admin.language' => \App\Http\Middleware\Admin\Language::class,
        'admin.indexTranslations' => \App\Http\Middleware\Admin\IndexTranslations::class,
        'admin.loginTranslations' => \App\Http\Middleware\Admin\LoginTranslations::class,
        'admin.userOptions' => \App\Http\Middleware\Admin\UserOptions::class,
        'admin.ip' => \App\Http\Middleware\Admin\Ip::class,
        'siteAnimator.options' => \App\Http\Middleware\Admin\SiteAnimator\Options::class,
        'admin.siteRouteVariables' => \App\Http\Middleware\Admin\SiteRouteVariables::class,
        'site.test' => \App\Http\Middleware\Site\SiteTest::class,
        'site.ip' => \App\Http\Middleware\Site\Ip::class,
        'site.siteRoute' => \App\Http\Middleware\Site\SiteRoute::class,
        'site.language' => \App\Http\Middleware\Site\Language::class,
        'site.settings' => \App\Http\Middleware\Site\Settings::class,
        'site.colors' => \App\Http\Middleware\Site\Colors::class,
        'site.page' => \App\Http\Middleware\Site\Page::class,
        'site.siteRouteVariables' => \App\Http\Middleware\Site\SiteRouteVariables::class,
        'api.blogData' => \App\Http\Middleware\Site\Api\Blog\BlogData::class,
        'api.siteRoute' => \App\Http\Middleware\Site\Api\SiteRoute::class,
        'api.language' => \App\Http\Middleware\Site\Api\Language::class,
        'api.authenticate' => \App\Http\Middleware\Admin\Authentication\Api\Authenticate::class,
        'mbAdmin.admin.ip' => \App\Http\Middleware\MbAdmin\Admin\Authentication\Ip::class,
        'codeAnalyser.admin.ip' => \App\Http\Middleware\CodeAnalyser\Admin\Authentication\Ip::class,
    ];
}
