<?php

    $version = 0.0000001;

$jsDir = env( 'SITE_ANIMATOR_JS_DIR' );

$files = array(
        
        '/common/js/admin/connection/adminConnectionModule.js',    
        '/common/js/admin/connection/adminUploadModule.js',    
        '/common/js/admin/connection/adminConnectionErrorModule.js',    
        '/common/js/admin/connection/adminConnectionErrorDialogModule.js',    
        '/common/js/admin/connection/adminCommunicationModule.js',    
        '/common/js/admin/main/adminBusyScreenModule.js',    
    
        '/common/js/admin/user/adminUserModule.js',
        
        $jsDir . '/admin/js/main/main.js',
        $jsDir . '/admin/js/main/adminSettingsModule.js',
        $jsDir . '/admin/js/main/layoutModule.js',
        $jsDir . '/admin/js/main/adminContentModule.js',

        $jsDir . '/admin/js/dialogs/adminDialogsModule.js',
        $jsDir . '/admin/js/dialogs/adminOkCancelDialogModule.js',
        $jsDir . '/admin/js/dialogs/adminErrorDialogModule.js',
        $jsDir . '/admin/js/dialogs/adminOutOfDateDialogModule.js',
        
        $jsDir . '/admin/js/tools/adminHoverTextModule.js',
        $jsDir . '/admin/js/tools/adminFlashTextModule.js',
        $jsDir . '/admin/js/tools/clipBoard/adminClipBoardModule.js',
        $jsDir . '/admin/js/tools/clipBoard/adminClipBoardJsonIndicatorModule.js',
        $jsDir . '/admin/js/tools/clipBoard/buttons/adminClipBoardButtonsModule.js',
        $jsDir . '/admin/js/tools/clipBoard/buttons/adminClipBoardButtonCancelModule.js',
        $jsDir . '/admin/js/tools/imageViewer/adminImageViewerModule.js',
        
        $jsDir . '/admin/js/validate/adminValidateModule.js',
        $jsDir . '/admin/js/translate/adminTranslateModule.js',

        $jsDir . '/admin/js/select/selectTool/adminSelectToolModule.js',
        $jsDir . '/admin/js/select/selectTool/adminSelectToolButtonsModule.js',
        $jsDir . '/admin/js/select/colorPickerModule.js',
        $jsDir . '/admin/js/select/adminSelectModule.js',
        $jsDir . '/admin/js/select/adminSelectItemModule.js',
        $jsDir . '/admin/js/select/treeSelect/adminTreeSelectModule.js',
        $jsDir . '/admin/js/select/treeSelect/adminTreeSelectItemModule.js',
        
        $jsDir . '/admin/js/buttons/adminButtonsModule.js',
        $jsDir . '/admin/js/buttons/adminPlayerButtonsModule.js',
        $jsDir . '/admin/js/buttons/adminDebuggerButtonModule.js',
        $jsDir . '/admin/js/buttons/adminUserOptionsButtonModule.js',
        $jsDir . '/admin/js/buttons/adminSiteSettingsButtonModule.js',
        $jsDir . '/admin/js/buttons/adminChatButtonModule.js',
        $jsDir . '/admin/js/buttons/adminShowNotPublicButtonModule.js',
        $jsDir . '/admin/js/buttons/adminClipboardButtonModule.js',
        $jsDir . '/admin/js/buttons/adminSelectToolButtonModule.js',
        $jsDir . '/admin/js/buttons/adminOpenSiteButtonModule.js',
        $jsDir . '/admin/js/buttons/adminLogOutButtonModule.js',
        $jsDir . '/admin/js/buttons/items/adminItemsButtonModule.js',
        $jsDir . '/admin/js/buttons/items/adminItemsButtonsModule.js',

        $jsDir . '/admin/js/animations/adminAnimationFramesModule.js',
        $jsDir . '/admin/js/animations/adminAnimationFramesDisplayModule.js',
        $jsDir . '/admin/js/animations/adminAnimationFramesDisplayPreviousButtonModule.js',
        $jsDir . '/admin/js/animations/adminAnimationFramesDisplayOptionsButtonModule.js',
        $jsDir . '/admin/js/animations/adminAnimationFramesDisplayNextButtonModule.js',
        $jsDir . '/admin/js/animations/adminAnimationFramesDisplayFrameModule.js',
    
        $jsDir . '/admin/js/items/common/adminItemsListItemModule.js',
        $jsDir . '/admin/js/items/common/adminItemsListGroupModule.js',
        $jsDir . '/admin/js/items/buttons/adminItemsSequenceButtonsModule.js',
        $jsDir . '/admin/js/items/buttons/adminItemsSequenceDownButtonModule.js',
        $jsDir . '/admin/js/items/buttons/adminItemsSequenceUpButtonModule.js',
        $jsDir . '/admin/js/items/adminItemsModule.js',
        $jsDir . '/admin/js/items/adminItemsHorizontalDividerModule.js',
        
        $jsDir . '/admin/js/items/routes/adminItemsListRoutesModule.js',
        $jsDir . '/admin/js/items/templates/adminItemsListTemplatesModule.js',
        $jsDir . '/admin/js/items/siteItems/adminItemsListSiteItemsModule.js',
        $jsDir . '/admin/js/items/pageParts/adminItemsListPagePartsModule.js',
        $jsDir . '/admin/js/items/translations/adminItemsListTranslationsModule.js',
        $jsDir . '/admin/js/items/lists/adminItemsListListsModule.js',
        $jsDir . '/admin/js/items/animations/adminItemsListAnimationsModule.js',
        $jsDir . '/admin/js/items/sequences/adminItemsListSequencesModule.js',
        $jsDir . '/admin/js/items/css/adminItemsListCssModule.js',
        $jsDir . '/admin/js/items/media/adminItemsListMediaModule.js',
        $jsDir . '/admin/js/items/colors/adminItemsListColorsModule.js',
                
        $jsDir . '/admin/js/edit/adminEditPanelModule.js',
        $jsDir . '/admin/js/edit/adminEditHorizontalDividerModule.js',
        
        $jsDir . '/admin/js/edit/content/adminEditPanelContentModule.js',
        $jsDir . '/admin/js/edit/content/adminEditPanelContentTitleModule.js',
        $jsDir . '/admin/js/edit/content/adminEditPanelContentMenuModule.js',
        $jsDir . '/admin/js/edit/content/adminEditPanelContentMessageModule.js',
        
        $jsDir . '/admin/js/edit/content/buttons/adminEditButtonsModule.js',
        $jsDir . '/admin/js/edit/content/buttons/adminEditButtonCancelModule.js',
        $jsDir . '/admin/js/edit/content/buttons/adminEditButtonDeleteModule.js',
        $jsDir . '/admin/js/edit/content/buttons/adminEditButtonInsertModule.js',
        $jsDir . '/admin/js/edit/content/buttons/adminEditButtonSelectModule.js',
        $jsDir . '/admin/js/edit/content/buttons/adminEditButtonDeSelectModule.js',
        $jsDir . '/admin/js/edit/content/buttons/adminEditButtonUpdateModule.js',
        $jsDir . '/admin/js/edit/content/buttons/adminEditButtonVersionModule.js',

        $jsDir . '/admin/js/edit/content/data/adminEditDataModule.js',
        $jsDir . '/admin/js/edit/content/data/adminEditDataStringModule.js',
        $jsDir . '/admin/js/edit/content/data/adminEditDataEmailModule.js',
        $jsDir . '/admin/js/edit/content/data/adminEditDataTextModule.js',
        $jsDir . '/admin/js/edit/content/data/adminEditDataBooleanModule.js',
        $jsDir . '/admin/js/edit/content/data/adminEditDataGroupModule.js',
        $jsDir . '/admin/js/edit/content/data/adminEditDataParentGroupModule.js',
        $jsDir . '/admin/js/edit/content/data/adminEditDataArrayModule.js',

        $jsDir . '/admin/js/edit/content/data/media/adminEditDataMediaModule.js',
        $jsDir . '/admin/js/edit/content/data/media/adminEditDataMediaImageModule.js',
        $jsDir . '/admin/js/edit/content/data/media/adminEditDataMediaSoundModule.js',
        
        $jsDir . '/admin/js/edit/content/data/json/adminEditDataJsonModule.js',
        $jsDir . '/admin/js/edit/content/data/json/adminEditDataJsonExpandableModule.js',
        $jsDir . '/admin/js/edit/content/data/json/adminEditDataJsonExpandableHeaderModule.js',
        $jsDir . '/admin/js/edit/content/data/json/adminEditDataJsonExpandableObjectsModule.js',
        $jsDir . '/admin/js/edit/content/data/json/adminEditDataJsonExpandableObjectValueModule.js',
        $jsDir . '/admin/js/edit/content/data/json/adminEditDataJsonExpandableArrayModule.js',
        $jsDir . '/admin/js/edit/content/data/json/adminEditDataJsonExpandableArrayValueModule.js',

        $jsDir . '/admin/js/edit/content/data/json/items/adminEditDataJsonTextModule.js',
        $jsDir . '/admin/js/edit/content/data/json/items/adminEditDataJsonRouteModule.js',
        $jsDir . '/admin/js/edit/content/data/json/items/adminEditDataJsonColorTextModule.js',
        $jsDir . '/admin/js/edit/content/data/json/items/adminEditDataJsonLanguageModule.js',
        $jsDir . '/admin/js/edit/content/data/json/items/adminEditDataJsonLanguageSelectModule.js',
        $jsDir . '/admin/js/edit/content/data/json/items/adminEditDataJsonTranslationModule.js',
        $jsDir . '/admin/js/edit/content/data/json/items/adminEditDataJsonCssModule.js',
        $jsDir . '/admin/js/edit/content/data/json/items/adminEditDataJsonListGroupModule.js',
        $jsDir . '/admin/js/edit/content/data/json/items/adminEditDataJsonColorModule.js',
        $jsDir . '/admin/js/edit/content/data/json/items/adminEditDataJsonMediaModule.js',
        $jsDir . '/admin/js/edit/content/data/json/items/adminEditDataJsonAnimationModule.js',
        $jsDir . '/admin/js/edit/content/data/json/items/adminEditDataJsonSequenceModule.js',
        $jsDir . '/admin/js/edit/content/data/json/items/typeSelect/adminEditDataJsonTypeSelectModule.js',
        $jsDir . '/admin/js/edit/content/data/json/items/typeSelect/adminEditDataJsonTypeSelectTypesModule.js',
        $jsDir . '/admin/js/edit/content/data/json/items/arrayIndexSelect/adminEditDataJsonArrayIndexSelectModule.js',
        $jsDir . '/admin/js/edit/content/data/json/items/arrayIndexSelect/adminEditDataJsonArrayIndexSelectIndexesModule.js',
        $jsDir . '/admin/js/edit/content/data/json/items/indexSelect/adminEditDataJsonIndexSelectModule.js',
        $jsDir . '/admin/js/edit/content/data/json/items/indexSelect/adminEditDataJsonIndexSelectIndexesModule.js',
        
    
        $jsDir . '/admin/js/edit/content/data/json/items/jsonSelect/adminEditDataJsonSelectModule.js',
        $jsDir . '/admin/js/edit/content/data/json/items/jsonSelect/adminEditDataJsonSelectOptionsModule.js',
        
        $jsDir . '/admin/js/edit/content/data/buttons/adminEditDataButtonsModule.js',
        $jsDir . '/admin/js/edit/content/data/buttons/adminEditDataButtonReplaceModule.js',
        $jsDir . '/admin/js/edit/content/data/buttons/adminEditDataButtonUpModule.js',
        $jsDir . '/admin/js/edit/content/data/buttons/adminEditDataButtonDownModule.js',
        $jsDir . '/admin/js/edit/content/data/buttons/adminEditDataButtonInsertModule.js',
        $jsDir . '/admin/js/edit/content/data/buttons/adminEditDataButtonCopyModule.js',
        $jsDir . '/admin/js/edit/content/data/buttons/adminEditDataButtonIndexModule.js',
        $jsDir . '/admin/js/edit/content/data/buttons/adminEditDataButtonArrayIndexModule.js',
        $jsDir . '/admin/js/edit/content/data/buttons/adminEditDataButtonTypeModule.js',
        $jsDir . '/admin/js/edit/content/data/buttons/adminEditDataButtonPasteModule.js',
        $jsDir . '/admin/js/edit/content/data/buttons/adminEditDataButtonInsertJsonModule.js',
        $jsDir . '/admin/js/edit/content/data/buttons/adminEditDataButtonDeleteModule.js',
        
        $jsDir . '/admin/js/edit/menu/adminEditMenuModule.js',
        $jsDir . '/admin/js/edit/menu/adminEditMenuItemModule.js',
               
        $jsDir . '/admin/js/edit/siteSettings/adminEditSiteSettingsModule.js',
        $jsDir . '/admin/js/edit/siteSettings/main/adminEditSiteSettingsMainModule.js',
        $jsDir . '/admin/js/edit/siteSettings/main/adminEditSiteSettingsMainUpdateModule.js',
        $jsDir . '/admin/js/edit/siteSettings/media/adminEditSiteSettingsMediaModule.js',
        $jsDir . '/admin/js/edit/siteSettings/media/adminEditSiteSettingsMediaUpdateModule.js',
    
        $jsDir . '/admin/js/edit/siteSettings/languages/adminEditSiteSettingsLanguagesModule.js',
        $jsDir . '/admin/js/edit/siteSettings/languages/adminEditSiteSettingsLanguageListItemModule.js',
        $jsDir . '/admin/js/edit/siteSettings/languages/adminEditSiteSettingsLanguagesChangeOrderModule.js',
        $jsDir . '/admin/js/edit/siteSettings/languages/adminEditSiteSettingsLanguagesUpdateModule.js',
        $jsDir . '/admin/js/edit/siteSettings/languages/adminEditSiteSettingsLanguageDeleteModule.js',
        $jsDir . '/admin/js/edit/siteSettings/languages/adminEditSiteSettingsLanguageInsertModule.js',
    
        $jsDir . '/admin/js/edit/siteSettings/byType/adminEditSiteSettingsByTypeModule.js',
        $jsDir . '/admin/js/edit/siteSettings/byType/adminEditSiteSettingsByTypeUpdateModule.js',
        
        $jsDir . '/admin/js/edit/adminUserOptions/adminEditAdminUserOptionsModule.js',
        $jsDir . '/admin/js/edit/adminUserOptions/main/adminEditAdminUserOptionsMainModule.js',
        $jsDir . '/admin/js/edit/adminUserOptions/main/adminEditAdminUserOptionsUserModule.js',
        $jsDir . '/admin/js/edit/adminUserOptions/main/adminEditAdminUserOptionsLanguageModule.js',
        $jsDir . '/admin/js/edit/adminUserOptions/main/adminEditAdminUserOptionsChangePasswordModule.js',
        $jsDir . '/admin/js/edit/adminUserOptions/main/adminEditAdminUserOptionsMainUpdateModule.js',
        $jsDir . '/admin/js/edit/adminUserOptions/appearance/adminEditAdminUserOptionsAppearanceModule.js',
        $jsDir . '/admin/js/edit/adminUserOptions/appearance/adminEditAdminUserOptionsAppearanceUpdateModule.js',
        $jsDir . '/admin/js/edit/adminUserOptions/edit/adminEditAdminUserOptionsEditModule.js',
        $jsDir . '/admin/js/edit/adminUserOptions/edit/adminEditAdminUserOptionsEditUpdateModule.js',
                
        $jsDir . '/admin/js/edit/routes/adminEditRoutesModule.js',
        $jsDir . '/admin/js/edit/routes/route/adminEditRouteModule.js',
        $jsDir . '/admin/js/edit/routes/route/adminEditRouteLanguageModule.js',
        $jsDir . '/admin/js/edit/routes/route/adminEditRouteParentModule.js',
        $jsDir . '/admin/js/edit/routes/route/adminEditRouteLinkModule.js',
        $jsDir . '/admin/js/edit/routes/route/adminEditRouteOptionsModule.js',
        $jsDir . '/admin/js/edit/routes/route/adminEditRouteInsertModule.js',        
        $jsDir . '/admin/js/edit/routes/route/adminEditRouteUpdateModule.js',
        $jsDir . '/admin/js/edit/routes/route/adminEditRouteDeleteModule.js',
        $jsDir . '/admin/js/edit/routes/group/adminEditRoutesGroupModule.js',
        $jsDir . '/admin/js/edit/routes/group/adminEditRoutesGroupInsertModule.js',
        $jsDir . '/admin/js/edit/routes/group/adminEditRoutesGroupUpdateModule.js',
        $jsDir . '/admin/js/edit/routes/group/adminEditRoutesGroupDeleteModule.js',

        $jsDir . '/admin/js/edit/siteItems/adminEditSiteItemsModule.js',
        $jsDir . '/admin/js/edit/siteItems/siteItem/adminEditSiteItemModule.js',
        $jsDir . '/admin/js/edit/siteItems/siteItem/adminEditSiteItemOptionsModule.js',
        $jsDir . '/admin/js/edit/siteItems/siteItem/adminEditSiteItemPartOptionsModule.js',
        $jsDir . '/admin/js/edit/siteItems/siteItem/adminEditSiteItemInsertModule.js',        
        $jsDir . '/admin/js/edit/siteItems/siteItem/adminEditSiteItemUpdateModule.js',        
        $jsDir . '/admin/js/edit/siteItems/siteItem/adminEditSiteItemDeleteModule.js',
        $jsDir . '/admin/js/edit/siteItems/group/adminEditSiteItemsGroupModule.js',
        $jsDir . '/admin/js/edit/siteItems/group/adminEditSiteItemsGroupInsertModule.js',
        $jsDir . '/admin/js/edit/siteItems/group/adminEditSiteItemsGroupUpdateModule.js',
        $jsDir . '/admin/js/edit/siteItems/group/adminEditSiteItemsGroupDeleteModule.js',
        $jsDir . '/admin/js/edit/siteItems/files/adminEditSiteItemFilesModule.js',
        $jsDir . '/admin/js/edit/siteItems/files/adminEditSiteItemFilesItemModule.js',
        $jsDir . '/admin/js/edit/siteItems/files/adminEditSiteItemFilesItemFilesModule.js',
        $jsDir . '/admin/js/edit/siteItems/files/adminEditSiteItemFilesItemFilesSourceModule.js',
        $jsDir . '/admin/js/edit/siteItems/children/adminEditSiteItemChildrenModule.js',
        $jsDir . '/admin/js/edit/siteItems/parents/adminEditSiteItemParentsModule.js',
        $jsDir . '/admin/js/edit/siteItems/parents/adminEditSiteItemParentsChildModule.js',
        $jsDir . '/admin/js/edit/siteItems/parents/adminEditSiteItemParentsItemParentsModule.js',

        $jsDir . '/admin/js/edit/templates/adminEditTemplatesModule.js',
        $jsDir . '/admin/js/edit/templates/template/adminEditTemplateModule.js',
        $jsDir . '/admin/js/edit/templates/template/adminEditTemplateTemplatePartModule.js',
        $jsDir . '/admin/js/edit/templates/template/adminEditTemplateOptionsModule.js',        
        $jsDir . '/admin/js/edit/templates/template/adminEditTemplateTemplatePartOptionsModule.js',        
        $jsDir . '/admin/js/edit/templates/template/adminEditTemplateInsertModule.js',        
        $jsDir . '/admin/js/edit/templates/template/adminEditTemplateUpdateModule.js',        
        $jsDir . '/admin/js/edit/templates/template/adminEditTemplateDeleteModule.js',
        $jsDir . '/admin/js/edit/templates/part/adminEditTemplatePartModule.js',
        $jsDir . '/admin/js/edit/templates/part/adminEditTemplatePartParentModule.js',
        $jsDir . '/admin/js/edit/templates/part/adminEditTemplatePartChildModule.js',
        $jsDir . '/admin/js/edit/templates/part/adminEditTemplatePartOptionsModule.js',        
        $jsDir . '/admin/js/edit/templates/part/adminEditTemplatePartInsertModule.js',        
        $jsDir . '/admin/js/edit/templates/part/adminEditTemplatePartUpdateModule.js',        
        $jsDir . '/admin/js/edit/templates/part/adminEditTemplatePartDeleteModule.js',
        $jsDir . '/admin/js/edit/templates/group/adminEditTemplatesGroupModule.js',
        $jsDir . '/admin/js/edit/templates/group/adminEditTemplatesGroupInsertModule.js',
        $jsDir . '/admin/js/edit/templates/group/adminEditTemplatesGroupUpdateModule.js',
        $jsDir . '/admin/js/edit/templates/group/adminEditTemplatesGroupDeleteModule.js',

        $jsDir . '/admin/js/edit/pageParts/adminEditPagePartsModule.js',
        $jsDir . '/admin/js/edit/pageParts/adminEditPagePartParentModule.js',
        $jsDir . '/admin/js/edit/pageParts/adminEditPagePartChildModule.js',
        $jsDir . '/admin/js/edit/pageParts/adminEditPagePartOptionsModule.js',
        $jsDir . '/admin/js/edit/pageParts/adminEditPagePartInsertModule.js',        
        $jsDir . '/admin/js/edit/pageParts/adminEditPagePartUpdateModule.js',        
        $jsDir . '/admin/js/edit/pageParts/adminEditPagePartDeleteModule.js',
    
        $jsDir . '/admin/js/edit/translations/adminEditTranslationsModule.js',
        $jsDir . '/admin/js/edit/translations/translation/adminEditTranslationModule.js',
        $jsDir . '/admin/js/edit/translations/translation/adminEditTranslationOptionsModule.js',
        $jsDir . '/admin/js/edit/translations/translation/adminEditTranslationInsertModule.js',        
        $jsDir . '/admin/js/edit/translations/translation/adminEditTranslationUpdateModule.js',        
        $jsDir . '/admin/js/edit/translations/translation/adminEditTranslationDeleteModule.js',
        $jsDir . '/admin/js/edit/translations/group/adminEditTranslationsGroupModule.js',
        $jsDir . '/admin/js/edit/translations/group/adminEditTranslationsGroupInsertModule.js',
        $jsDir . '/admin/js/edit/translations/group/adminEditTranslationsGroupUpdateModule.js',
        $jsDir . '/admin/js/edit/translations/group/adminEditTranslationsGroupDeleteModule.js',

        $jsDir . '/admin/js/edit/lists/adminEditListsModule.js',
        $jsDir . '/admin/js/edit/lists/list/adminEditListModule.js',
        $jsDir . '/admin/js/edit/lists/list/adminEditListOptionsModule.js',        
        $jsDir . '/admin/js/edit/lists/list/adminEditListInsertModule.js',        
        $jsDir . '/admin/js/edit/lists/list/adminEditListUpdateModule.js',        
        $jsDir . '/admin/js/edit/lists/list/adminEditListDeleteModule.js',
        $jsDir . '/admin/js/edit/lists/group/adminEditListsGroupModule.js',
        $jsDir . '/admin/js/edit/lists/group/adminEditListsGroupOptionsModule.js',
        $jsDir . '/admin/js/edit/lists/group/adminEditListsGroupInsertModule.js',
        $jsDir . '/admin/js/edit/lists/group/adminEditListsGroupUpdateModule.js',
        $jsDir . '/admin/js/edit/lists/group/adminEditListsGroupDeleteModule.js',

        $jsDir . '/admin/js/edit/animations/adminEditAnimationsModule.js',
        $jsDir . '/admin/js/edit/animations/animation/adminEditAnimationModule.js',
        $jsDir . '/admin/js/edit/animations/animation/adminEditAnimationOptionsModule.js',        
        $jsDir . '/admin/js/edit/animations/animation/adminEditAnimationInsertModule.js',        
        $jsDir . '/admin/js/edit/animations/animation/adminEditAnimationUpdateModule.js',        
        $jsDir . '/admin/js/edit/animations/animation/adminEditAnimationDeleteModule.js',
        $jsDir . '/admin/js/edit/animations/group/adminEditAnimationsGroupModule.js',
        $jsDir . '/admin/js/edit/animations/group/adminEditAnimationsGroupInsertModule.js',
        $jsDir . '/admin/js/edit/animations/group/adminEditAnimationsGroupUpdateModule.js',
        $jsDir . '/admin/js/edit/animations/group/adminEditAnimationsGroupDeleteModule.js',

        $jsDir . '/admin/js/edit/sequences/adminEditSequencesModule.js',
        $jsDir . '/admin/js/edit/sequences/sequence/adminEditSequenceModule.js',
        $jsDir . '/admin/js/edit/sequences/sequence/adminEditSequenceOptionsModule.js',        
        $jsDir . '/admin/js/edit/sequences/sequence/adminEditSequenceInsertModule.js',        
        $jsDir . '/admin/js/edit/sequences/sequence/adminEditSequenceUpdateModule.js',        
        $jsDir . '/admin/js/edit/sequences/sequence/adminEditSequenceDeleteModule.js',
        $jsDir . '/admin/js/edit/sequences/group/adminEditSequencesGroupModule.js',
        $jsDir . '/admin/js/edit/sequences/group/adminEditSequencesGroupInsertModule.js',
        $jsDir . '/admin/js/edit/sequences/group/adminEditSequencesGroupUpdateModule.js',
        $jsDir . '/admin/js/edit/sequences/group/adminEditSequencesGroupDeleteModule.js',

        $jsDir . '/admin/js/edit/media/adminEditMediaModule.js',
        $jsDir . '/admin/js/edit/media/media/adminEditMediaItemModule.js',
        $jsDir . '/admin/js/edit/media/media/adminEditMediaOptionsModule.js',        
        $jsDir . '/admin/js/edit/media/media/adminEditMediaInsertModule.js',        
        $jsDir . '/admin/js/edit/media/media/adminEditMediaUpdateModule.js',        
        $jsDir . '/admin/js/edit/media/media/adminEditMediaDeleteModule.js',
        $jsDir . '/admin/js/edit/media/group/adminEditMediaGroupModule.js',
        $jsDir . '/admin/js/edit/media/group/adminEditMediaGroupInsertModule.js',
        $jsDir . '/admin/js/edit/media/group/adminEditMediaGroupUpdateModule.js',
        $jsDir . '/admin/js/edit/media/group/adminEditMediaGroupDeleteModule.js',

        $jsDir . '/admin/js/edit/css/adminEditCssModule.js',
        $jsDir . '/admin/js/edit/css/css/adminEditCssItemModule.js',
        $jsDir . '/admin/js/edit/css/css/adminEditCssOptionsModule.js',        
        $jsDir . '/admin/js/edit/css/css/adminEditCssInsertModule.js',        
        $jsDir . '/admin/js/edit/css/css/adminEditCssUpdateModule.js',        
        $jsDir . '/admin/js/edit/css/css/adminEditCssDeleteModule.js',
        $jsDir . '/admin/js/edit/css/group/adminEditCssGroupModule.js',
        $jsDir . '/admin/js/edit/css/group/adminEditCssGroupInsertModule.js',
        $jsDir . '/admin/js/edit/css/group/adminEditCssGroupUpdateModule.js',
        $jsDir . '/admin/js/edit/css/group/adminEditCssGroupDeleteModule.js',

        $jsDir . '/admin/js/edit/colors/adminEditColorsModule.js',
        $jsDir . '/admin/js/edit/colors/color/adminEditColorModule.js',
        $jsDir . '/admin/js/edit/colors/color/adminEditColorOptionsModule.js',        
        $jsDir . '/admin/js/edit/colors/color/adminEditColorInsertModule.js',        
        $jsDir . '/admin/js/edit/colors/color/adminEditColorUpdateModule.js',        
        $jsDir . '/admin/js/edit/colors/color/adminEditColorDeleteModule.js',
        $jsDir . '/admin/js/edit/colors/group/adminEditColorsGroupModule.js',
        $jsDir . '/admin/js/edit/colors/group/adminEditColorsGroupInsertModule.js',
        $jsDir . '/admin/js/edit/colors/group/adminEditColorsGroupUpdateModule.js',
        $jsDir . '/admin/js/edit/colors/group/adminEditColorsGroupDeleteModule.js',

        $jsDir . '/admin/js/chat/adminChatModule.js',
        
        $jsDir . '/admin/js/debugger/adminDebuggerModule.js',
        $jsDir . '/admin/js/debugger/adminDebuggerPlayerInfoModule.js',
        $jsDir . '/admin/js/debugger/adminDebuggerDebugModule.js',
        $jsDir . '/admin/js/debugger/adminDebuggerOptionsModule.js',
        
        '/common/js/admin/login/loginDialogModule.js',
        '/common/js/admin/login/sendResetPasswordEmailDialogModule.js',
        
        '/common/js/admin/errors/adminErrorsModule.js',

        $jsDir . '/site/js/main/settingsModule.js',
        $jsDir . '/site/js/main/contentModule.js',
        $jsDir . '/site/js/main/cssModule.js'
        
        
    );
    
    
?>

@foreach ($files as $file)
<script type="text/javascript" src="{{ URL::to( '/public' . $file ) }}<?php echo '?version=' . $version; ?>"></script>
@endforeach


